
# Define Variable
variables:
  TEST_IMAGE: node:16.18.1-alpine3.15
  BUILD_IMAGE: docker:dind
  ENV_FILE: $ENV_FILE_BACKEND

before_script:
  - echo "$ENV_FILE_BACKEND" > .env

stages:
  - test
  - build
  - deploy

test-job:
  stage: test
  image: $TEST_IMAGE
  tags:
    - docker
  before_script:
    - apk add make
    - npm install jest -g
    - npm install
  script:
    - make -B test 

build-job:
  stage: build
  tags:
    - ubuntu
  script:
    - docker login registry.khitkabar.xyz:5443 -u khitkabar -p khit.kabar.registry.123
    - docker build . --file Dockerfile --tag registry.khitkabar.xyz:5443/$CI_PROJECT_NAME:$CI_COMMIT_BRANCH
    - docker push registry.khitkabar.xyz:5443/$CI_PROJECT_NAME:$CI_COMMIT_BRANCH

deploy-dev-job:
  stage: deploy
  image: docker/compose
  only:
    - dev
  tags:
    - ubuntu
  script:
    - docker login registry.khitkabar.xyz:5443 -u khitkabar -p khit.kabar.registry.123
    - source .server.env
    - docker-compose up -d

deploy-prod-job:
  stage: deploy
  tags:
    - ubuntu
  only:
    - master
  script:
    - source .server.env
    - docker-compose up -d